Algoritmo "Algoritmo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2026
Var
base ,altura ,area :real
multiplicacao ,divisao :real
operacao :caracter
Inicio
Escreval("Dê um valor a base do triângulo:")
Leia(base)
Escreval("Dê um valor a altura do triângulo: ")
Leia(altura)

area <- base*altura/2

Escreval("A area do triângulo equivale a: ", area)

Fimalgoritmo