Algoritmo "Olá mundo"
// Disciplina   : Programação de algoritmos
// Professor   : Wagner Cesar Vieira
// Descrição   : Neste algoritmo, vou exibir um alô mundo.
// Autor(a)    : Lucas Augusto Galati Machado
// Data atual  : 09/03/2026
Var
// Aqui vou descrever as variáveis do meu algoritmo
nome: caracter
idade: inteiro
altura: real
status: logico
Inicio
    Escreval("Algoritmo de pessoas")
    Escreva("Qual o seu nome: ")
    Leia(nome)
    
    Escreva("Informe sua idade: ")
    Leia(idade)
    
    Escreva("Qual a sua altura em metros: ")
    Leia(altura)
    
    Escreva("Informe o seu status: ")
    Leia(status)
    status <- verdadeiro
    
    Escreval("O nome da pessoa é ",nome)
    Escreval("A idade é ",idade)
    Escreval("A altura é ",altura)
    Escreval("Seu status é ",status)

Fimalgoritmo